server:
  port: 9090
  #ssl:
  #  enabled: true # Uses self-signed certificate because no key-store configuration is specified.

internal.lb.uri: http://localhost
spring:
  cloud:
    gateway:
      corsConfigurations:
        '[/**]':
          allowedOrigins:
            - "http://localhost:3000"
          allowedHeaders: "*"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
        discovery:
          locator:
            enabled: true
      routes:
        - id: employees
          uri: ${internal.lb.uri}:9000
          predicates:
            - Path=/api/employees/**
        - id: customers
          uri: ${internal.lb.uri}:9001
          predicates:
            - Path=/api/customers/**
        - id: suppliers
          uri: ${internal.lb.uri}:9002
          predicates:
            - Path=/api/suppliers/**
        - id: webapp
          uri: ${internal.lb.uri}:9003
          predicates:
            - Path=/**

